name: GKE Deploy via Artifact Registry
description: Deploys containers to GKE via Google Artifact Registry
inputs:
  GOOGLE_CLOUD_PROJECT_ID:
    description: Google Cloud Project ID you want to use.
    required: true
  GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY:
    description: Google Cloud Service Account KEY
    required: true
  DOCKER_BUILD_ARGS:
    description: If you want to inject build params to docker build step.
    required: true
  GKE_ZONE:
    description: GKE Zone
    required: true
  GKE_CLUSTER:
    description: Name of the cluster
    required: true
  ARTIFACT_REGISTRY_REGION:
    description: Google Artifact Registry region you want to use
    required: true
  ARTIFACT_REGISTRY_REPO:
    description: Google artifact Registry repository you want to store your build image in
    required: true
  ARTIFACT_REGISTRY_IMAGE:
    description: Google Artifact Registry image
    required: true
  IMAGE_TAG:
    description: Tag for your image
    required: true
  IMAGE_ENV:
    description: Deployment environment (e.g. preview, stage, prod)
    required: true
  GKE_CONFIG_DIR:
    description: K8S config file directory.
    required: true
  GKE_IMAGE_TEMPLATE:
    description: GKE Deployment Image Template
    required: true
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
    - name: Auth Google Cloud
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
      with:
        credentials_json: ${{ inputs.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3
      with:
        project_id: ${{ inputs.GOOGLE_CLOUD_PROJECT_ID }}
    - name: Setup Docker Auth
      shell: bash
      env:
        ARTIFACT_REGISTRY_REGION: ${{ inputs.ARTIFACT_REGISTRY_REGION }}
      run: |
        gcloud --quiet auth configure-docker "$ARTIFACT_REGISTRY_REGION-docker.pkg.dev"
    - name: Setup AR image tag url
      id: ar_tag
      shell: bash
      env:
        ARTIFACT_REGISTRY_REGION: ${{ inputs.ARTIFACT_REGISTRY_REGION }}
        GOOGLE_CLOUD_PROJECT_ID: ${{ inputs.GOOGLE_CLOUD_PROJECT_ID }}
        ARTIFACT_REGISTRY_REPO: ${{ inputs.ARTIFACT_REGISTRY_REPO }}
        ARTIFACT_REGISTRY_IMAGE: ${{ inputs.ARTIFACT_REGISTRY_IMAGE }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
      run: |
        echo "ar_image_tag=$ARTIFACT_REGISTRY_REGION-docker.pkg.dev/$GOOGLE_CLOUD_PROJECT_ID/$ARTIFACT_REGISTRY_REPO/$ARTIFACT_REGISTRY_IMAGE:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
    - name: Build & push image (cached)
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
      with:
        context: .
        push: true
        tags: ${{ steps.ar_tag.outputs.ar_image_tag }}
        build-args: |
          version=${{ inputs.IMAGE_TAG }}
          env=${{ inputs.IMAGE_ENV }}
        cache-from: type=gha,scope=${{ github.repository }}-${{ inputs.ARTIFACT_REGISTRY_IMAGE }}
        cache-to: type=gha,scope=${{ github.repository }}-${{ inputs.ARTIFACT_REGISTRY_IMAGE }},mode=max
    - name: Setup GKE Credentials
      uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395 # v3
      with:
        cluster_name: ${{ inputs.GKE_CLUSTER }}
        location: ${{ inputs.GKE_ZONE }}
    - name: Deploy image from AR to GKE
      shell: bash
      env:
        GKE_CONFIG_DIR: ${{ inputs.GKE_CONFIG_DIR }}
        GKE_IMAGE_TEMPLATE: ${{ inputs.GKE_IMAGE_TEMPLATE }}
        AR_IMAGE_TAG: ${{ steps.ar_tag.outputs.ar_image_tag }}
      run: |-
        cd "$GKE_CONFIG_DIR"
        kustomize edit set image "$GKE_IMAGE_TEMPLATE=$AR_IMAGE_TAG"
        kubectl apply -k .
