name: GKE Deploy via Artifact Registry
description: Deploys containers to GKE via Google Artifact Registry
inputs:
  GOOGLE_CLOUD_PROJECT_ID:
    description: Google Cloud Project ID you want to use.
    required: true
  GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY:
    description: Google Cloud Service Account KEY
    required: true
  DOCKER_BUILD_ARGS:
    description: If you want to inject build params to docker build step.
    required: true
  GKE_ZONE:
    description: GKE Zone
    required: true
  GKE_CLUSTER:
    description: Name of the cluster
    required: true
  ARTIFACT_REGISTRY_REGION:
    description: Google Artifact Registry region you want to use
    required: true
  ARTIFACT_REGISTRY_REPO:
    description: Google artifact Registry repository you want to store your build image in
    required: true
  ARTIFACT_REGISTRY_IMAGE:
    description: Google Artifact Registry image
    required: true
  IMAGE_TAG:
    description: Tag for your image
    required: true
  IMAGE_ENV:
    description: Deployment environment (e.g. preview, stage, prod)
    required: true
  GKE_CONFIG_DIR:
    description: K8S config file directory.
    required: true
  GKE_IMAGE_TEMPLATE:
    description: GKE Deployment Image Template
    required: true
runs:
  using: composite
  steps:
    - name: Auth Google Cloud
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ inputs.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        project_id: ${{ inputs.GOOGLE_CLOUD_PROJECT_ID }}
    - name: Setup Docker Auth
      shell: bash
      run: |
        gcloud --quiet auth configure-docker ${{ inputs.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev
    - name: Setup AR image tag url
      shell: bash
      run: echo "ar_image_tag=${{ inputs.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ inputs.GOOGLE_CLOUD_PROJECT_ID }}/${{ inputs.ARTIFACT_REGISTRY_REPO }}/${{ inputs.ARTIFACT_REGISTRY_IMAGE }}:${{ inputs.IMAGE_TAG }}" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build & push image (cached)
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.ar_image_tag }}
        build-args: |
          version=${{ inputs.IMAGE_TAG }}
          env=${{ inputs.IMAGE_ENV }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Setup GKE Credentials
      uses: google-github-actions/get-gke-credentials@v3
      with:
        cluster_name: ${{ inputs.GKE_CLUSTER }}
        location: ${{ inputs.GKE_ZONE }}
    - name: Deploy image from AR to GKE
      shell: bash
      run: |-
        cd ${{ inputs.GKE_CONFIG_DIR }}
        kustomize edit set image ${{ inputs.GKE_IMAGE_TEMPLATE }}=${{ env.ar_image_tag }}
        kubectl apply -k .
